dependencies:
  dns_simple_server:
    url: github.com/toitlang/pkg-dns-simple-server
    version: ^0.2.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.9.0
  lightbug:
    url: github.com/lightbug-io/toit-lightbug
    version: ^0.10.0
